AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Metadata:
  'AWS::ServerlessRepo::Application':
    Name: rds-excel-support
    Labels:
      - piping
      - lambda
      - rds-master-etl
    SemanticVersion: 1.2.0
Parameters:
  ImageUri:
    Description: 'Mandatory: ECR Uri for the image. If not present, then create and push using the sam-imagebuilder.yaml in the github https://github.com/aws-samples/spark-on-aws-lambda '
    Type: String
    Default: ''
  LambdaTimeout:
    Description: 'Optional: Maximum Lambda invocation runtime in seconds. (min 1 - 900 max)'
    Default: 900
    Type: Number
  LambdaMemory:
    Description: 'Optional: Lambda memory in MB (min 128 - 10,240 max).'
    Default: 3008
    Type: Number
  LambdaName:
    Description: 'Optional: Override the default Lambda function name.'
    Type: String
    Default: ''
  ENDPOINT:
    Type: String
  DBNAME:
    Type: String
  REGION:
    Type: String
  SecretName:
    Type: String
  BucketName:
    Type: String
    Description: Name of the S3 bucket
  NameTable:
    Type: String
  SuccessSNSTopic:
    Type: String
  FailureSNSTopic:
    Type: String
  SchemaName:
    Type: String
Resources:


  LambdaExecutionRole:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: 'Allow'
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      ManagedPolicyArns:
        - 'arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole'
#        - 'arn:aws:iam::aws:policy/service-role/AWSLambdaVPCAccessExecutionRole'
        - 'arn:aws:iam::aws:policy/service-role/AWSLambdaSQSQueueExecutionRole'
      Policies:
        - PolicyName: 'ECRAccess'
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - ecr:GetAuthorizationToken
                Resource: '*'
              - Effect: Allow
                Action:
                  - ecr:BatchCheckLayerAvailability
                  - ecr:GetDownloadUrlForLayer
                  - ecr:BatchGetImage
                Resource:
                  Fn::Sub:
                    - "arn:aws:ecr:${Region}:${Account}:repository/${RepositoryName}"
                    - Region: !Select [3, !Split [".", !Ref ImageUri ]]
                      Account: !Select [0, !Split [".", !Ref ImageUri ]]
                      RepositoryName: !Select [1, !Split ["/", !Select [ 0, !Split [":", !Select [5, !Split [".", !Ref ImageUri ]]]]]]
#        - PolicyName: 'S3Access'
#          PolicyDocument:
#            Version: '2012-10-17'
#            Statement:
#              - Effect: 'Allow'
#                Action:
#                  - 's3:*'
#                Resource:
#                  - !Sub 'arn:aws:s3:::${BucketName}/support/destination/*'
#                  - !Sub 'arn:aws:s3:::${BucketName}/support/processed/*'
        - PolicyName: 'RDSAccess'
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: 'Allow'
                Action:
                  - 'rds-db:*'
                Resource: !Sub 'arn:aws:rds:${AWS::Region}:${AWS::AccountId}:db:${DBNAME}'
        - PolicyName: cloudwatch
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: 'Allow'
                Action:
                  - 'logs:CreateLogGroup'
                  - 'logs:CreateLogStream'
                  - 'logs:PutLogEvents'
                Resource: !Sub 'arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/lambda/${AWS::StackName}:*'
        - PolicyName: 'SecretsAccess'
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: 'Allow'
                Action:
                  - 'secretsmanager:GetSecretValue'
                  - 'secretsmanager:DescribeSecret'
                Resource: !Sub 'arn:aws:secretsmanager:${AWS::Region}:${AWS::AccountId}:secret:rdspiping-*'
        - PolicyName: 'SNSAccess'
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: 'Allow'
                Action:
                  - 'sns:Publish'
                Resource:
                  - !Sub 'arn:aws:sns:${AWS::Region}:${AWS::AccountId}:SuccessFullMasterTable'
                  - !Sub 'arn:aws:sns:${AWS::Region}:${AWS::AccountId}:FailureFullMasterTable'
        - PolicyName: SQSReceiveAccess
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - 'sqs:ReceiveMessage'
                  - 'sqs:DeleteMessage'
                  - 'sqs:GetQueueAttributes'
                  - 'sqs:ChangeMessageVisibility'
                Resource:
                  - !ImportValue QueueURL-Support-ARN
                  - !ImportValue QueueURL-WB-ARN

  LambdaFunction:
    Type: AWS::Serverless::Function
    Properties:
      PackageType: Image
      FunctionName: !Ref LambdaName
      ImageUri: !Ref ImageUri
      Description: Lambda to run Spark containers
      Timeout: !Ref LambdaTimeout
      MemorySize: !Ref LambdaMemory
      Role: !GetAtt LambdaExecutionRole.Arn
      Architectures:
        - x86_64
      Environment:
        Variables:
          ENDPOINT: !Ref ENDPOINT
          PORT: 5432
          REGION: !Ref REGION
          DBNAME: !Ref DBNAME
          DESTINATION_BUCKETNAME: !Ref BucketName
          SECRET_NAME: !Ref SecretName
          NAME_TABLE: !Ref NameTable
          SUCCESS_SNS_TOPIC_ARN: !Ref SuccessSNSTopic
          FAILURE_SNS_TOPIC_ARN: !Ref FailureSNSTopic
          SCHEMA_NAME: !Ref SchemaName

      Events:
        QueueSupportEvent:
          Type: SQS
          Properties:
            Queue: !ImportValue QueueURL-Support-ARN
            BatchSize: 10
            Enabled: true
        QueueWBEvent:
          Type: SQS
          Properties:
            Queue: !ImportValue QueueURL-WB-ARN
            BatchSize: 10
            Enabled: true

Outputs:
  LambdaFunctionArn:
    Description: Lambda Function ARN
    Value: !GetAtt LambdaFunction.Arn