AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Globals:
  Function:
    Timeout: 10
    MemorySize: 3008

Parameters:
  ImageUri:
    Type: String

Resources:
  LambdaExecutionRole:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: 'Allow'
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      ManagedPolicyArns:
        - 'arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole'
      Policies:
        # Policy for ECR access to pull container images
        - PolicyName: 'ECRAccess'
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - ecr:GetAuthorizationToken
                Resource: '*'
              - Effect: Allow
                Action:
                  - ecr:BatchCheckLayerAvailability
                  - ecr:GetDownloadUrlForLayer
                  - ecr:BatchGetImage
                Resource:
                  Fn::Sub:
                    - "arn:aws:ecr:${Region}:${Account}:repository/${RepositoryName}"
                    - Region: !Select [3, !Split [".", !Ref ImageUri ]]
                      Account: !Select [0, !Split [".", !Ref ImageUri ]]
                      RepositoryName: !Select [1, !Split ["/", !Select [ 0, !Split [":", !Select [5, !Split [".", !Ref ImageUri ]]]]]]
        # Policy for CloudWatch logs
        - PolicyName: cloudwatch
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: 'Allow'
                Action:
                  - 'logs:CreateLogGroup'
                  - 'logs:CreateLogStream'
                  - 'logs:PutLogEvents'
                Resource: !Sub 'arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/lambda/${AWS::StackName}:*'
        # Policy for Kinesis stream access
        - PolicyName: KinesisAccess
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - kinesis:GetRecords
                  - kinesis:GetShardIterator
                  - kinesis:DescribeStream
                  - kinesis:ListShards
                Resource: !GetAtt MessageStream.Arn
        # Policy for SQS DLQ access
        - PolicyName: SQSAccess
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - sqs:SendMessage
                Resource: !GetAtt FailedSensorReadingDLQ.Arn

  LambdaFunction:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: rust-cargolambda
      BuildProperties:
        Binary: kinesis-lambda
    Properties:
      PackageType: Image
      FunctionName: serverless-rust-KinesisProcessor
      ImageUri: !Ref ImageUri
      Role: !GetAtt LambdaExecutionRole.Arn
      Architectures:
        - arm64
      EventInvokeConfig:
        MaximumRetryAttempts: 2
        MaximumEventAgeInSeconds: 300
        DestinationConfig:
          OnFailure:
            Type: SQS
            Destination: !GetAtt FailedSensorReadingDLQ.Arn
      Events:
        Stream:
          Type: Kinesis
          Properties:
            Stream: !GetAtt MessageStream.Arn
            BatchSize: 100
            StartingPosition: LATEST

  MessageStream:
    Type: AWS::Kinesis::Stream
    Properties:
      ShardCount: 1

  FailedSensorReadingDLQ:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: serverless-rust-KinesisSensorDLQ

Outputs:
  StreamARN:
    Description: "Stream ARN"
    Value: !GetAtt MessageStream.Arn