# More information about the configuration file can be found here:
# https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-sam-cli-config.html
version = 0.1

[default]
[default.global.parameters]
stack_name = "kinesis-lambda-rust"

[default.build.parameters]
cached = true
parallel = true

[default.validate.parameters]
lint = true

[default.deploy.parameters]
capabilities = "CAPABILITY_IAM"
confirm_changeset = true
resolve_s3 = true
s3_prefix = "kinesis-lambda-rust"
region = "us-east-1"
image_repositories = []
parameter_overrides = "ImageUri=\"881490115226.dkr.ecr.us-east-1.amazonaws.com/rust-stream:v07-kinesis-rust-redis-arm64\" SnowflakeUsername=\"RUSTSPARK\" SnowflakePassword=\"Snowflake2025.*\" SnowflakeAccount=\"jnvzape-hkc13589\" SnowflakeRole=\"ACCOUNTADMIN\" SnowflakeWarehouse=\"COMPUTE_WH\" SnowflakeDatabase=\"RUSTSTREAMMING\" SnowflakeSchema=\"RUSTSTREAM\" SnowflakeTable=\"SENSOR_READINGS\" BatchSize=\"100\" MaxConnections=\"4\" MaxBatchSize=\"2000\" MinBatchsize=\"100\" TimeoutMS=\"100\""

[default.package.parameters]
resolve_s3 = true

[default.sync.parameters]
watch = true

[default.local_start_api.parameters]
warm_containers = "EAGER"

[default.local_start_lambda.parameters]
warm_containers = "EAGER"