AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Excel file processor Lambda function

Globals:
  Function:
    LoggingConfig:
      LogFormat: JSON
    Tags:
      Application: ExcelProcessor
      Environment: !Ref AWS::StackName

Parameters:
  BucketName:
    Type: String
    Description: Name of the S3 bucket to monitor
  SheetName:
    Type: String
    Description: Name of the sheet within the Excel file
  FolderSourcePath:
    Type: String
    Description: Folder path to monitor for Excel files
  FolderDestinationPath:
    Type: String
    Description: Folder path to save the CSV files
  SkipRow:
    Type: String
    Description: Skip row number in the Excel file
  AccountID:
    Type: String
    Description: Account ID of the destination S3 bucket
  ColumnsToInsideTrim:
    Type: String
    Description: Columns to trim in the Excel file
  FunctionName:
    Type: String
    Default: lambda-sheet-isos-x86-64
Resources:


  LambdaLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub /aws/lambda/${ExcelSupportFunction}
      RetentionInDays: 5
    UpdateReplacePolicy: Delete
    DeletionPolicy: Delete


  ExcelSupportFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Ref FunctionName
      CodeUri: .
      Handler: logicExcel.App::handleRequest
      Runtime: java17
      Timeout: 60
      MemorySize: 1024
      Architectures:
        - x86_64
      Policies:
        - S3FullAccessPolicy:
            BucketName: !Ref BucketName
        - Statement:
            - Effect: Allow
              Action:
                - logs:CreateLogGroup
                - logs:CreateLogStream
                - logs:PutLogEvents
                - logs:DeleteLogGroup
              Resource: !Sub arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/lambda/${AWS::StackName}-*
      Environment:
        Variables:
          SHEET_NAME: !Ref SheetName
          BUCKET_NAME: !Ref BucketName
          FOLDER_SOURCE_PATH: !Ref FolderSourcePath
          FOLDER_DESTINATION_PATH: !Ref FolderDestinationPath
          JAVA_TOOL_OPTIONS: -XX:+TieredCompilation -XX:TieredStopAtLevel=1
          SKIP_ROW: !Ref SkipRow
          EXPECTED_ACCOUNT_ID: !Ref AccountID
          COLUMNS_TO_INSIDE_TRIM: !Ref ColumnsToInsideTrim

  LambdaInvokePermission:
    Type: AWS::Lambda::Permission
    DependsOn:
      - ExcelSupportFunction
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !Ref ExcelSupportFunction
      Principal: s3.amazonaws.com
      SourceArn: !Sub arn:aws:s3:::${BucketName}

Outputs:
  FunctionArn:
    Description: ARN of the Lambda function
    Value: !GetAtt ExcelSupportFunction.Arn
  FunctionName:
    Description: Name of the Lambda function
    Value: !Ref ExcelSupportFunction
  BucketName:
    Description: Name of the created S3 bucket
    Value: !Ref BucketName